blocks_schema = {
    'number': 'bigint',
    'hash': 'string',
    'parent_hash': 'string',
    'nonce': 'string',
    'sha3_uncles': 'string',
    'logs_bloom': 'string',
    'transactions_root': 'string',
    'state_root': 'string',
    'receipts_root': 'string',
    'miner': 'string',
    'difficulty': 'decimal(38,9)',
    'total_difficulty': 'decimal(38,9)',
    'size': 'bigint',
    'extra_data': 'string',
    'gas_limit': 'bigint',
    'gas_used': 'bigint',
    'timestamp': 'timestamp',
    'transaction_count': 'bigint',
    'base_fee_per_gas': 'bigint',
}

transactions_schema = {
    'hash': 'string',
    'nonce': 'bigint',
    'transaction_index': 'bigint',
    'from_address': 'string',
    'to_address': 'string',
    'value': 'decimal(38,9)',
    'gas': 'bigint',
    'gas_price': 'bigint',
    'input': 'string',
    'receipt_cumulative_gas_used': 'bigint',
    'receipt_gas_used': 'bigint',
    'receipt_contract_address': 'string',
    'receipt_root': 'string',
    'receipt_status': 'bigint',
    'block_timestamp': 'timestamp',
    'block_number': 'bigint',
    'block_hash': 'string',
    'max_fee_per_gas': 'bigint',
    'max_priority_fee_per_gas': 'bigint',
    'transaction_type': 'bigint',
    'receipt_effective_gas_price': 'bigint',
}

contracts_schema = {
    'address': 'string',
    'bytecode': 'string',
    'function_sighashes': 'array<string>',
    'is_erc20': 'boolean',
    'is_erc721': 'boolean',
    'block_timestamp': 'timestamp',
    'block_number': 'bigint',
    'block_hash': 'string',
}

logs_schema = {
    'log_index': 'bigint',
    'transaction_hash': 'string',
    'transaction_index': 'bigint',
    'address': 'string',
    'data': 'string',
    'topics': 'array<string>',
    'block_timestamp': 'timestamp',
    'block_number': 'bigint',
    'block_hash': 'string',
}

traces_schema = {
    'transaction_hash': 'string',
    'transaction_index': 'bigint',
    'from_address': 'string',
    'to_address': 'string',
    'value': 'decimal(38,9)',
    'input': 'string',
    'output': 'string',
    'trace_type': 'string',
    'call_type': 'string',
    'reward_type': 'string',
    'gas': 'bigint',
    'gas_used': 'bigint',
    'subtraces': 'bigint',
    'trace_address': 'string',
    'error': 'string',
    'status': 'bigint',
    'block_timestamp': 'timestamp',
    'block_number': 'bigint',
    'block_hash': 'string',
    'trace_id': 'string',
}

tokens_schema = {
    'address': 'string',
    'symbol':  'string',
    'name':  'string',
    'decimals':  'string',
    'total_supply':  'string',
    'block_timestamp': 'timestamp',
    'block_number':  'bigint',
    'block_hash':  'string',
}

token_transfers_schema = {
    'token_address': 'string',
    'from_address': 'string',
    'to_address': 'string',
    'value': 'string',
    'transaction_hash': 'string',
    'log_index': 'bigint',
    'block_timestamp': 'timestamp',
    'block_number': 'bigint',
    'block_hash': 'string',
}
