#!/bin/bash

NAME="${HN_JOB_NAME:=default}"
JOB_NUM_JOBS="${HN_BATCH_JOB_ARRAY_SIZE:=0}"
NODE_INDEX="${AWS_BATCH_JOB_ARRAY_INDEX:=0}"
START_BLOCK_INDEX="${HN_START_BLOCK_INDEX:=-1}"
END_BLOCK_INDEX="${HN_END_BLOCK_INDEX:=-1}"
PROVIDER="${HN_PROVIDER:=http://44.207.25.161:8584}"

python /ethereum-etl/main.py -name ${NAME} "${START_BLOCK_INDEX:+-s $START_BLOCK_INDEX}" "${END_BLOCK_INDEX:+-e $END_BLOCK_INDEX}" -n ${JOB_NUM_JOBS} -i ${NODE_INDEX} -provider ${PROVIDER}
