#!/bin/bash

NAME="${HN_JOB_NAME:=default}"
JOB_NUM_JOBS="${HN_BATCH_JOB_ARRAY_SIZE:=0}"
NODE_INDEX="${AWS_BATCH_JOB_ARRAY_INDEX:=0}"
START_BLOCK_INDEX="${HN_START_BLOCK_INDEX:=-1}"
END_BLOCK_INDEX="${HN_END_BLOCK_INDEX:=-1}"

PROVIDER_ARR=("http://44.207.25.161:8584" "http://44.209.138.14:8584" "http://44.208.109.105:8584")
PROVIDER_INDEX=$(( NODE_INDEX % 3 ))
PROVIDER="${PROVIDER_ARR[$PROVIDER_INDEX]}"
echo "$PROVIDER_INDEX"
echo "$PROVIDER"

python /ethereum-etl/main.py -name ${NAME} "${START_BLOCK_INDEX:+-s $START_BLOCK_INDEX}" "${END_BLOCK_INDEX:+-e $END_BLOCK_INDEX}" -n ${JOB_NUM_JOBS} -i ${NODE_INDEX} -provider ${PROVIDER}
